version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/yourdatabase
      - SPRING_DATASOURCE_USERNAME=yourusername
      - SPRING_DATASOURCE_PASSWORD=yourpassword
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/yourmongodb
    depends_on:
      - database
      - mongodb

  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=yourdatabase

  mongodb:
    image: mongo:latest
